# See https://goreleaser.com for documentation
builds:
  - env:
      # goreleaser does not work with CGO
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    tags:
      # default backend, gpgme, requires CGO, making it
      # incompatible with goreleaser
      - containers_image_openpgp
    binary: "{{ .ProjectName }}_v{{ .Version }}"

dockers:
  - image_templates:
      - "ghcr.io/moio/{{.ProjectName}}:{{ .Tag }}"
      - "ghcr.io/moio/{{.ProjectName}}:v{{ .Major }}"
      - "ghcr.io/moio/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/moio/{{.ProjectName}}:latest"
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"
